traindata <-read.table("x_train.txt")
dim(traindata)
head(traindata)
trainlabel <- read.table("y_train.txt")
tabel(trainlabel)
trainsubject <- read.table("subject_train.txt")
data <- read.table("x_test.txt")
dim(data)
testlabel <-read.table("y_test.txt")
table(testlabel)
testsubject <- read.table("subject_test.txt")
data <- rbind(traindata, testdata)
dim(data)
datasubject <-rbind(trainsubject, testsubject)
dim(data)
